### PR TITLE
[G2M] Colors prop as function fix; Pie fix for 100% slice white divider left when hiding data in legend

### LINKED ISSUE #132: Pie chart rendering discrepancy
The issue is originally found from overlord's geo cohort report. The pie chart shows the fraction of the entire circle when the number is 100%

Could be overlord specific.
 
Screen Shot 2021-06-10 at 9 07 15 PM

### PR DESCRIPTION
**Pull request by geoerika**
Closes #132
**Fixes:**

1. Fixed applying colors prop as a function for all charts - code logic was still missing after the last PR
2. Added storybooks for color as function for each chart type
3. Pie - removed white divider left when hiding data in legend when we have one slice left at 100 %
4. Added commit-watch to github/workflows master.yml

Before:
Screen Shot 2021-06-12 at 10 25 29 PM
After:
Screen Shot 2021-06-12 at 10 25 53 PM

### CODE REVIEW

File: src/components/pie-chart/index.js [hunk 1]
```diff
@@ -80,7 +89,11 @@ const PieChart = ({
     const { finalIndexBy, finalDataKey } = processPieDataKeys({ data, indexBy, dataKey })
     const aggregatedData = aggregateData({ data, keys: [finalDataKey], indexBy: finalIndexBy, groupByKey, valueKey, type: 'sum' })
     const nivoData = convertPieDataToNivo({ data: aggregatedData, indexBy: finalIndexBy, dataKey: finalDataKey })
-    const baseColors = typeof colors === 'function' || !colors.length ? processColors(data.length, colorType, colorParam) : colors
+    let baseColors = colors.length ? colors : processColors(data.length, colorType, colorParam)
+
+    if (typeof colors === 'function') {
+      baseColors = nivoData.map(d => colors(d))
```
Comment (woozyking) [inline src/components/pie-chart/index.js:95]: not overly important but this can be simplified as:

```suggestion
      baseColors = nivoData.map(colors)
```

**Review by woozyking — APPROVED** [review]

File: stories/color.stories.js [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+    })
+    return (
+      <ResponsiveChartWrapper>
+        <BarChart
+          title={ title }
+          data={ barChartData }
+          axisBottomLegendLabel='Address City'
+          axisLeftLegendLabel='Visitors'
+          groupMode='grouped'
+          colors={(d) => colorsMap[d]}
```
Comment (DoParkEQ) [inline stories/color.stories.js:34]: Question: how is it different than feeding an array of colors?

Comment (woozyking) [reply stories/color.stories.js:34]: `colors` param is taken in as a function, so it's referred that way in the component (see around `if (typeof colors === 'function')`)

Comment (geoerika) [reply stories/color.stories.js:34]: If you just feed a list of colours, the colours would not be all the time the same for Top 5, when you switch tabs. Tamires designed the tabs to always use the same colours for top 5 in overlord. 
Regardless, the nivo charts by themselves could handle colors as functions as default, but Shane added a complex system of setting the default chart-system colours and the default colors as function didn't work anymore, which was practically a bug. Tamires used the function form of colors to set the colours to always match between the charts, so top 5 data in pie clors would always match top 5 in bar chart as colours. The only reason it worked so far, it was because we used only top 5 and Shanes code defaulted to the colour scheme and function in charts, which would do the same thing. Once I did top 10 thought the scheme didn't work anymore, we don't have enough colors in chart-system and the colours were mismatched between the charts.

Comment (geoerika) [reply stories/color.stories.js:34]: What we do now, we use the colors as function to match specific data attribute value to a specific color, that is how the colors as function works. And as I said, it was not working before, it was a bug that needed to be fixed.

Comment (DoParkEQ) [reply stories/color.stories.js:34]: I see. I'll probably have to take a look deeper, but from my understanding if nivo is capable of handling colors in both array and function form, it might be able to directly plugged into the nivo chart?

**Review by DoParkEQ — APPROVED** [review]

File: stories/color.stories.js (hunk 2 above)
Comment (geoerika) [reply stories/color.stories.js]: Yeah, it might be, but the problem was to keep Shane's process of hiding items in the legend intact, and that's what I did here. I can look over it later if I can make it simpler, although it didn't seem to me when I tried to fix the whole thing.
