### PR TITLE
Legend: trimming fix for special characters

### LINKED ISSUE #97: Legend - label trimming off when special characters are present
**Current Behaviour**
When Legend labels contain special characters trimming doesn't work properly; labels are not adjusted to their entire length when chart is enlarged

**Desired Outcome**
Legend labels should extend properly when they contain special characters

### PR DESCRIPTION
**Pull request by geoerika**
Closes #97
- package.json: installed html-entities
- utils/index.js: imported XmlEntities from html-entities
- utils/index.js: added entities.decode to getTextSize
- scatter-chart-data.js: modified ids to include special characters
- CHANGELOG.md: added legend trimming fix

### CODE REVIEW

File: src/shared/data/scatter-chart-data.js [hunk 1]
```diff
@@ -1,32 +1,25 @@
...
-  { id: 'Third Legend Longer', x: 70, y: 0.550 },
-  { id: 'Third Legend Longer', x: 80, y: 1 },
-  // { id: 'Fourth Legend', x: 20, y: 0.2 },
-  // { id: 'Fourth Legend', x: 30, y: 0.425 },
-  // { id: 'Fourth Legend', x: 40, y: 0.375 },
-  // { id: 'Fourth Legend', x: 50, y: 0.575 },
-  // { id: 'Fourth Legend', x: 60, y: 0.6 },
-  // { id: 'Fourth Legend', x: 70, y: 0.550 },
-  // { id: 'Fourth Legend', x: 80, y: 0.9 },
+  { id: 'Arts & Entertainment', x: 20, y: 0.35 },
```
Comment (woozyking) [inline src/shared/data/scatter-chart-data.js:2]: just noticed this file. all these non-implementation files (such as test data for stories) should be moved out of `src/`. otherwise these are only increasing the package size.

File: package.json [hunk 2]
```diff
@@ -24,6 +24,7 @@
     "d3-scale": "^3.2.1",
     "d3-shape": "^1.3.7",
     "d3-time": "^2.0.0",
+    "html-entities": "^1.3.1",
```
Comment (woozyking) [inline package.json:27]: any `package.json` needs to have pairing `yarn.lock` update. make sure to include it.

File: src/shared/data/scatter-chart-data.js (hunk 1 above)
Comment (geoerika) [reply src/shared/data/scatter-chart-data.js:2]: I am thinking to move all data folder in stories. Is that ok?
